# Generated by Django 2.2.3 on 2019-07-22 03:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spots_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
