# Generated by Django 2.2.3 on 2019-07-22 14:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_spots_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
