# Generated by Django 2.2.3 on 2019-07-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_spots_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
