# Generated by Django 2.2.3 on 2019-08-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUserActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useractions_spot_id', to='api.Spots')),
                ('type_user_action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useractions_type_user_action_id', to='api.TypeUserActions')),
            ],
        ),
        migrations.CreateModel(
            name='SpotTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spottags_user_action_id', to='api.Tags')),
                ('user_action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spottags_user_action_id', to='api.UserActions')),
            ],
        ),
    ]
