# Generated by Django 2.2.3 on 2019-08-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_spottags_typeuseractions_useractions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeUserActions',
            new_name='TypesUserAction',
        ),
    ]
