# Generated by Django 2.2.3 on 2019-08-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190803_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spottags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='spottags',
            old_name='user_action_id',
            new_name='user_action',
        ),
        migrations.RenameField(
            model_name='useractions',
            old_name='spot_id',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='useractions',
            old_name='type_user_action_id',
            new_name='type_user_action',
        ),
    ]
