# Generated by Django 2.2.4 on 2019-08-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190803_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='full_address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spots',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
